### ISSUE TITLE
Cannot log in to Google account

### ISSUE THREAD

**Issue by Kalela** [MDSADABWASIM/You#1]
When attempting to log in to my Google account to get my data from Google. I get this prompt. Then get stuck in the sign in with google page unless I close the app. I'm running android 11.
![Screenshot_20200929-181456](https://user-images.githubusercontent.com/33759757/94578584-98597100-0280-11eb-840a-9e06e937900c.png)

**Comment by MDSADABWASIM** [comment]
Hi, @Kalela I'm going to update this app for android 11 in a few days please look for an update and then try to do that. Thanks for your feedback.
